
package com.ws.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.0
 * Sun May 13 22:33:28 EET 2018
 * Generated source version: 2.3.0
 */

@XmlRootElement(name = "count", namespace = "http://ws.ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "count", namespace = "http://ws.ws.com/")

public class Count {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

