
package com.ws.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.0
 * Sun May 13 22:33:28 EET 2018
 * Generated source version: 2.3.0
 */

@XmlRootElement(name = "productCount", namespace = "http://ws.ws.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productCount", namespace = "http://ws.ws.com/")

public class ProductCount {


}

